---
# Install some useful utilities

- name: add backports repo
  apt_repository:
    repo="deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"
    state=present
    update_cache=yes

- name: install httpie
  pip: name=httpie state=present

- name: install utilities from apt
  apt: name={{ item }} state=present
  with_items:
    - jq=1.4-2.1~ubuntu14.04.1
    - htop
    - mysql-client-5.6
    - mysql-utilities
    - python-mysqldb
    - curl
    - tree
    - emacs24-nox
    - vim
    - sysstat
    - traceroute
    - rsyslog-gnutls
